; Arquivo de configuracao do PlatformIO
; Abrir este projeto no VSCode com a extensao PlatformIO instalada
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Bibliotecas necessarias (o PlatformIO baixa sozinho na 1a compilacao)
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    madhephaestus/ESP32Servo @ ^3.0.4
    bblanchon/ArduinoJson @ ^7.1.0
